
namespace sgl::shaders {
    const char* line_batch_shader_src = 
    "#version 460 core\n"
    "layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;\n"
    "layout(rgba8ui, binding = 0) uniform uimage2D imgOutput;\n"
    "struct Line\n"
    "{\n"
    "   uvec2 start;\n"
    "   uvec2 end;\n"
    "};\n"
    "layout(std430, binding = 1) buffer LineData\n"
    "{\n"
    "   uvec4 color;\n"
    "   Line[] lines;\n"
    "};\n"
    "void main() {\n"
    "   if(gl_GlobalInvocationID.y >= lines.length()) return;\n"
    "   uint coord = gl_GlobalInvocationID.x;\n"
    "   Line line = lines[gl_GlobalInvocationID.y];\n"
    "   float pos = float(coord) / 32.f / 16.f;\n"
    "   ivec2 texelCoord = ivec2(vec2(line.start) + (vec2(line.end)-vec2(line.start))*pos);\n"
    
    "   imageStore(imgOutput, texelCoord, color);\n"
    "}";

    const char* tri_batch_shader_src = 
    "#version 460 core\n"
    "layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;\n"
    "layout(rgba8ui, binding = 0) uniform uimage2D imgOutput;\n"
    "struct Tri\n"
    "{\n"
    "   vec2 v0;\n"
    "   vec2 v1;\n"
    "   vec2 v2;\n"
    "};\n"
    "layout(std430, binding = 1) buffer TriData\n"
    "{\n"
    "   uvec4 color;\n"
    "   Tri[] tris;\n"
    "};\n"

    "vec3 barycentric(vec2 point, vec2 v0, vec2 v1, vec2 v2) {\n"
    "   float denominator = ((v0.x - v2.x) * (v1.y - v2.y)) - ((v1.x - v2.x) * (v0.y - v2.y));\n"
    "   if(abs(denominator) < 1e-6) return vec3(-1.f,-1.f,-1.f);\n"

    "   float lambda0 = ((point.x - v2.x) * (v1.y - v2.y) - (point.y - v2.y) * (v1.x - v2.x)) / denominator;\n"
    "   float lambda1 = ((point.y - v2.y) * (v0.x - v2.x) - (point.x - v2.x) * (v0.y - v2.y)) / denominator;\n"
    "   float lambda2 = 1.f - lambda0 - lambda1;\n"
    "   return vec3(lambda0, lambda1, lambda2);\n"
    "}\n"

    "void main() {\n"
    "   if(gl_GlobalInvocationID.z >= tris.length()) return;\n"
    "   ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);\n"
    "   vec2 coord = vec2(texelCoord) + vec2(0.5f, 0.5f);\n"
    "   Tri tri = tris[gl_GlobalInvocationID.z];\n"
    "   if(any(lessThan(coord, min(min(tri.v0, tri.v1), tri.v2)))) return;\n"
    "   if(any(greaterThan(coord, max(max(tri.v0, tri.v1), tri.v2)))) return;\n"
    "   vec3 baryc = barycentric(coord, tri.v0, tri.v1, tri.v2);\n"
    "   if(all(greaterThanEqual(baryc, vec3(0)))){\n"
    //"       imageStore(imgOutput, texelCoord, color);\n"
    "       imageStore(imgOutput, texelCoord, uvec4(int(baryc.x*255), int(baryc.y*255), 0, 255));\n"
    "   }\n"
    "}";

    const char* tri_batch_depthtest_projection_shader_src = 
    "#version 460 core\n"
    "layout (local_size_x = 4, local_size_y = 4, local_size_z = 1) in;\n"
    "layout(rgba8ui, binding = 0) uniform uimage2D imgOutput;\n"
    "layout(r32f, binding = 1) uniform image2D imgDepthOutput;\n"
    "layout(rgba8ui, binding = 7) uniform uimage2D imgTexture;\n"
    "struct Tri4D\n"
    "{\n"
    "   vec4 v0;\n"
    "   vec4 v1;\n"
    "   vec4 v2;\n"
    "};\n"
    "struct Tri3D\n"
    "{\n"
    "   vec3 v0;\n"
    "   vec3 v1;\n"
    "   vec3 v2;\n"
    "};\n"
    "struct PointData\n"
    "{\n"
    "   vec4 o;\n"
    "   vec4 t;\n"
    "   vec2 tex;\n"
    "};\n"
    "struct IndexData\n"
    "{\n"
    "   uvec3 v;\n"
    "   uvec3 uv;\n"
    "   uvec3 no;\n"
    "};\n"
    "layout(std430, binding = 2) buffer DrawData\n"
    "{\n"
    "   mat4 modelViewProj;\n"
    "   vec3 camera;"
    "   int curr_index;"
    "};\n"
    "layout(std430, binding = 3) buffer IndexesData\n"
    "{\n"
    "   IndexData[] indexes;\n"
    "};\n"
    "layout(std430, binding = 4) buffer PointsData\n"
    "{\n"
    "   PointData[] points;\n"
    "};\n"
    "layout(std430, binding = 5) buffer UvData\n"
    "{\n"
    "   vec2[] UV;\n"
    "};\n"
    "layout(std430, binding = 6) buffer NormalData\n"
    "{\n"
    "   vec3[] normals;\n"
    "};\n"
    "vec3 barycentric(vec2 point, vec3 v0, vec3 v1, vec3 v2) {\n"
    "   float denominator = ((v0.x - v2.x) * (v1.y - v2.y)) - ((v1.x - v2.x) * (v0.y - v2.y));\n"
    "   if(abs(denominator) < 1e-6) return vec3(-1.f,-1.f,-1.f);\n"

    "   float lambda0 = ((point.x - v2.x) * (v1.y - v2.y) - (point.y - v2.y) * (v1.x - v2.x)) / denominator;\n"
    "   float lambda1 = ((point.y - v2.y) * (v0.x - v2.x) - (point.x - v2.x) * (v0.y - v2.y)) / denominator;\n"
    "   float lambda2 = 1.f - lambda0 - lambda1;\n"
    "   return vec3(lambda0, lambda1, lambda2);\n"
    "}\n"

    "void main() {\n"
    "   if(curr_index + gl_GlobalInvocationID.z > indexes.length()) return;\n"
    //"   const vec3 camera = normalize(vec3(modelViewProj[0][2],modelViewProj[1][2],modelViewProj[2][2]));\n"
    "   const IndexData index = indexes[curr_index + gl_GlobalInvocationID.z];\n"
    "   vec2 coord = vec2(gl_GlobalInvocationID.xy) + vec2(0.5f, 0.5f);\n"
    "   const PointData[3] pd = {points[index.v.x], points[index.v.y], points[index.v.z]};\n"
    "   const Tri3D tri_world = Tri3D(vec3(pd[0].o), vec3(pd[1].o), vec3(pd[2].o));\n"
    "   vec3 normal = normalize(cross(tri_world.v1 - tri_world.v2, tri_world.v1 - tri_world.v0));\n"
    "   float dot = dot(camera, normal);\n"
    "   if(dot >= cos(radians(30))) return;\n"
    "   const Tri3D tri = Tri3D(vec3(pd[0].t), vec3(pd[1].t), vec3(pd[2].t));\n"
    //"   imageStore(imgOutput, ivec2(tri.v0), uvec4(0,255,0,255));\n"
    "   const vec2 mins = vec2(min(min(tri.v0, tri.v1), tri.v2));\n"
    "   coord += (ivec2(mins)/8)*8;\n"
    //"   if(any(greaterThan(coord, vec2(max(max(tri.v0, tri.v1), tri.v2))) )) return;\n"
    "   const vec3 baryc = barycentric(coord, tri.v0, tri.v1, tri.v2);\n"
    "   if(all(greaterThanEqual(baryc, vec3(0)))){\n"
    "       const float dist = tri.v0.z * baryc.x + tri.v1.z * baryc.y + tri.v2.z * baryc.z;\n"
    "       if(dist > 0) return;"
    "       const vec2 uvx = UV[index.uv.x] * baryc.x + UV[index.uv.y] * baryc.y + UV[index.uv.z] * baryc.z;\n"
    "       const vec2 uv = vec2(1,-1)*uvx + vec2(0,1);\n"
    "       const ivec2 texelCoord = ivec2(coord);\n"
    "       memoryBarrierImage();\n"
    "       const float odist = imageLoad(imgDepthOutput, texelCoord).r;\n"
    "       if(dist < odist){\n"
    "           imageStore(imgDepthOutput, texelCoord, vec4(dist));\n"
    "           const uvec4 color = imageLoad(imgTexture, ivec2(uv*vec2(imageSize(imgTexture))));\n"
    //"           imageStore(imgOutput, texelCoord, uvec4(int(baryc.x*255), int(baryc.y*255), int(dot*255), 255));\n"
    //"           imageStore(imgOutput, texelCoord, color);\n"
    "           imageStore(imgOutput, texelCoord, uvec4(uvec2(uv*255), 0, 255));\n"
    "       }\n"
    "   }\n"
    "}\n";

}